### PR TITLE
Add data view fixes

### LINKED ISSUE #64: Main table fixup
Some enhancements for the main data table:

- [ ] The very first column should always default to be run number.
- [ ] Duration is currently shown in seconds - this can be converted to a simple hours/minutes/seconds string as appropriate.
- [ ] Once the model has update the table, calling `resizeColumnsToContents()` would make it look much nicer.

### PR DESCRIPTION
**Pull request by EthanDevlinSTFC**
Re-order columns based on preferences
Allow user to save order preferences
Fix display of duration
Have columns automatically resize
closes #64

### CODE REVIEW

File: frontend/datagathering.cpp [hunk 1]
```diff
@@ -99,11 +99,24 @@ void MainWindow::handle_result_cycles(HttpRequestWorker *worker)
...
+        QString columnHeading;
+        for (auto i = 0; i < desiredHeader_.count(); i++)
+        {
+            for (auto j = 0; j < ui_->runDataTable->horizontalHeader()->count(); j++)
+            {
+                logIndex = ui_->runDataTable->horizontalHeader()->logicalIndex(j);
+                columnHeading = ui_->runDataTable->horizontalHeader()->model()->headerData(logIndex, Qt::Horizontal).toString();
+                if (desiredHeader_[i] == columnHeading)
+                    ui_->runDataTable->horizontalHeader()->swapSections(j, i);
+            }
```
Comment (trisyoungs) [inline frontend/datagathering.cpp]: Can remove the temporary variable:
```suggestion
        for (auto i = 0; i < desiredHeader_.count(); ++i)
        {
            for (auto j = 0; j < ui_->runDataTable->horizontalHeader()->count(); ++j)
            {
                logIndex = ui_->runDataTable->horizontalHeader()->logicalIndex(j);
                if (desiredHeader_[i] == ui_->runDataTable->horizontalHeader()->model()->headerData(logIndex, Qt::Horizontal).toString();)
                    ui_->runDataTable->horizontalHeader()->swapSections(j, i);
            }
```
Also note use of prefix over postfix increment.

**Review by trisyoungs — APPROVED** [review]
One tiny suggested change, otherwise :+1:
